### ISSUE TITLE
how to use openapiclient "./openapi"

### ISSUE THREAD

**Issue by 978740431** [nftstorage/go-client#2]
https://github.com/nftstorage/go-client/blob/main/docs/NFTStorageAPI.md#store
I don't know openapiclient ". /openapi" library from where, can you tell me the specific steps to use it?

**Comment by alanshaw** [comment]
I _think_ you should just be able to:

```go
import (
  nftstorage "github.com/nftstorage/go-client"
)
```

...and then use `nftstorage` instead of `openapiclient` in the example you linked:
